SET search_path TO "Budget_Execution";

CREATE TABLE public."grbs"
  (kbk VARCHAR(60)PRIMARY KEY,
  title TEXT NOT NULL);

CREATE TABLE RZ2016
  (kbk VARCHAR(60) PRIMARY KEY,
  grbs_kbk VARCHAR(60) REFERENCES public.GRBS(kbk),
  title TEXT);

CREATE TABLE RZ2017
  (kbk VARCHAR(60) PRIMARY KEY,
  grbs_kbk VARCHAR(60) REFERENCES public.GRBS(kbk),
  title TEXT);

CREATE TABLE RZ2018
  (kbk VARCHAR(60) PRIMARY KEY,
  grbs_kbk VARCHAR(60) REFERENCES public.GRBS(kbk),
  title TEXT);

CREATE TABLE RZ2019
  (kbk VARCHAR(60) PRIMARY KEY,
  grbs_kbk VARCHAR(60) REFERENCES public.GRBS(kbk),
  title TEXT);

CREATE TABLE RZ2020
  (kbk VARCHAR(60) PRIMARY KEY,
  grbs_kbk VARCHAR(60) REFERENCES public.GRBS(kbk),
  title TEXT);

CREATE TABLE RZ2021
  (kbk VARCHAR(60) PRIMARY KEY,
  grbs_kbk VARCHAR(60) REFERENCES public.GRBS(kbk),
  title TEXT);

CREATE TABLE PR2016
  (kbk VARCHAR(60) PRIMARY KEY,
  rz_kbk VARCHAR(60) REFERENCES RZ2016(kbk),
  title TEXT);

CREATE TABLE PR2017
  (kbk VARCHAR(60) PRIMARY KEY,
  rz_kbk VARCHAR(60) REFERENCES RZ2017(kbk),
  title TEXT);

CREATE TABLE PR2018
  (kbk VARCHAR(60) PRIMARY KEY,
  rz_kbk VARCHAR(60) REFERENCES RZ2018(kbk),
  title TEXT);

CREATE TABLE PR2019
  (kbk VARCHAR(60) PRIMARY KEY,
  rz_kbk VARCHAR(60) REFERENCES RZ2019(kbk),
  title TEXT);

CREATE TABLE PR2020
  (kbk VARCHAR(60) PRIMARY KEY,
  rz_kbk VARCHAR(60) REFERENCES RZ2020(kbk),
  title TEXT);

CREATE TABLE PR2021
  (kbk VARCHAR(60) PRIMARY KEY,
  rz_kbk VARCHAR(60) REFERENCES RZ2021(kbk),
  title TEXT);

CREATE TABLE SR_PROG2016
  (kbk VARCHAR(60) PRIMARY KEY,
  code VARCHAR(60),
  UNIQUE (code));

CREATE TABLE SR_PROG2017
  (kbk VARCHAR(60) PRIMARY KEY,
  code VARCHAR(60),
  UNIQUE (code));

CREATE TABLE SR_PROG2018
  (kbk VARCHAR(60) PRIMARY KEY,
  code VARCHAR(60),
  UNIQUE (code));

CREATE TABLE SR_PROG2019
  (kbk VARCHAR(60) PRIMARY KEY,
  code VARCHAR(60),
  UNIQUE (code));

CREATE TABLE SR_PROG2020
  (kbk VARCHAR(60) PRIMARY KEY,
  code VARCHAR(60),
  UNIQUE (code));

CREATE TABLE SR_PROG2021
  (kbk VARCHAR(60) PRIMARY KEY,
  code VARCHAR(60),
  UNIQUE (code));

CREATE TABLE GOSPROGRAM_SR2016
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2016(kbk),
  id_prog VARCHAR(60) REFERENCES SR_PROG2016(code),
  title TEXT,
  UNIQUE (id_prog));

CREATE TABLE GOSPROGRAM_SR2017
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2017(kbk),
  id_prog VARCHAR(60) REFERENCES SR_PROG2017(code),
  title TEXT,
  UNIQUE (id_prog));

CREATE TABLE GOSPROGRAM_SR2018
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2018(kbk),
  id_prog VARCHAR(60) REFERENCES SR_PROG2018(code),
  title TEXT,
  UNIQUE (id_prog));

CREATE TABLE GOSPROGRAM_SR2019
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2019(kbk),
  id_prog VARCHAR(60) REFERENCES SR_PROG2019(code),
  title TEXT,
  UNIQUE (id_prog));

CREATE TABLE GOSPROGRAM_SR2020
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2020(kbk),
  id_prog VARCHAR(60) REFERENCES SR_PROG2020(code),
  title TEXT,
  UNIQUE (id_prog));

CREATE TABLE GOSPROGRAM_SR2021
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2021(kbk),
  id_prog VARCHAR(60) REFERENCES SR_PROG2021(code),
  title TEXT,
  UNIQUE (id_prog));

CREATE TABLE SUBPROGRAM_SR2016
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2016(kbk),
  code_subprog VARCHAR(60) REFERENCES SR_PROG2016(code),
  prog_kbk VARCHAR(60) REFERENCES GOSPROGRAM_SR2016(kbk),
  title TEXT,
  UNIQUE (code_subprog));

CREATE TABLE SUBPROGRAM_SR2017
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2017(kbk),
  code_subprog VARCHAR(60) REFERENCES SR_PROG2017(code),
  prog_kbk VARCHAR(60) REFERENCES GOSPROGRAM_SR2017(kbk),
  title TEXT,
  UNIQUE (code_subprog));

CREATE TABLE SUBPROGRAM_SR2018
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2018(kbk),
  code_subprog VARCHAR(60) REFERENCES SR_PROG2018(code),
  prog_kbk VARCHAR(60) REFERENCES GOSPROGRAM_SR2018(kbk),
  title TEXT,
  UNIQUE (code_subprog));

CREATE TABLE SUBPROGRAM_SR2019
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2019(kbk),
  code_subprog VARCHAR(60) REFERENCES SR_PROG2019(code),
  prog_kbk VARCHAR(60) REFERENCES GOSPROGRAM_SR2019(kbk),
  title TEXT,
  UNIQUE (code_subprog));

CREATE TABLE SUBPROGRAM_SR2020
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2020(kbk),
  code_subprog VARCHAR(60) REFERENCES SR_PROG2020(code),
  prog_kbk VARCHAR(60) REFERENCES GOSPROGRAM_SR2020(kbk),
  title TEXT,
  UNIQUE (code_subprog));

CREATE TABLE SUBPROGRAM_SR2021
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2021(kbk),
  code_subprog VARCHAR(60) REFERENCES SR_PROG2021(code),
  prog_kbk VARCHAR(60) REFERENCES GOSPROGRAM_SR2021(kbk),
  title TEXT,
  UNIQUE (code_subprog));

CREATE TABLE MAIN_EVENT_SR2016
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2016(kbk),
  code_main_event VARCHAR(60) REFERENCES SR_PROG2016(code),
  subprog_kbk VARCHAR(60) REFERENCES SUBPROGRAM_SR2016(kbk),
  title TEXT,
  UNIQUE (code_main_event));

CREATE TABLE MAIN_EVENT_SR2017
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2017(kbk),
  code_main_event VARCHAR(60) REFERENCES SR_PROG2017(code),
  subprog_kbk VARCHAR(60) REFERENCES SUBPROGRAM_SR2017(kbk),
  title TEXT,
  UNIQUE (code_main_event));

CREATE TABLE MAIN_EVENT_SR2018
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2018(kbk),
  code_main_event VARCHAR(60) REFERENCES SR_PROG2018(code),
  subprog_kbk VARCHAR(60) REFERENCES SUBPROGRAM_SR2018(kbk),
  title TEXT,
  UNIQUE (code_main_event));

CREATE TABLE MAIN_EVENT_SR2019
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2019(kbk),
  code_main_event VARCHAR(60) REFERENCES SR_PROG2019(code),
  subprog_kbk VARCHAR(60) REFERENCES SUBPROGRAM_SR2019(kbk),
  title TEXT,
  UNIQUE (code_main_event));

CREATE TABLE MAIN_EVENT_SR2020
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2020(kbk),
  code_main_event VARCHAR(60) REFERENCES SR_PROG2020(code),
  subprog_kbk VARCHAR(60) REFERENCES SUBPROGRAM_SR2020(kbk),
  title TEXT,
  UNIQUE (code_main_event));

CREATE TABLE MAIN_EVENT_SR2021
  (kbk VARCHAR(60) PRIMARY KEY REFERENCES SR_PROG2021(kbk),
  code_main_event VARCHAR(60) REFERENCES SR_PROG2021(code),
  subprog_kbk VARCHAR(60) REFERENCES SUBPROGRAM_SR2021(kbk),
  title TEXT,
  UNIQUE (code_main_event));

CREATE TABLE SR2016
  (kbk VARCHAR(60) PRIMARY KEY,
  pr_kbk VARCHAR(60) REFERENCES PR2016(kbk),
  sr_prog_kbk VARCHAR(60) REFERENCES SR_PROG2016(kbk));

CREATE TABLE SR2017
  (kbk VARCHAR(60) PRIMARY KEY,
  pr_kbk VARCHAR(60) REFERENCES PR2017(kbk),
  sr_prog_kbk VARCHAR(60) REFERENCES SR_PROG2017(kbk));

CREATE TABLE SR2018
  (kbk VARCHAR(60) PRIMARY KEY,
  pr_kbk VARCHAR(60) REFERENCES PR2018(kbk),
  sr_prog_kbk VARCHAR(60) REFERENCES SR_PROG2018(kbk));

CREATE TABLE SR2019
  (kbk VARCHAR(60) PRIMARY KEY,
  pr_kbk VARCHAR(60) REFERENCES PR2019(kbk),
  sr_prog_kbk VARCHAR(60) REFERENCES SR_PROG2019(kbk));

CREATE TABLE SR2020
  (kbk VARCHAR(60) PRIMARY KEY,
  pr_kbk VARCHAR(60) REFERENCES PR2020(kbk),
  sr_prog_kbk VARCHAR(60) REFERENCES SR_PROG2020(kbk));

CREATE TABLE SR2021
  (kbk VARCHAR(60) PRIMARY KEY,
  pr_kbk VARCHAR(60) REFERENCES PR2021(kbk),
  sr_prog_kbk VARCHAR(60) REFERENCES SR_PROG2021(kbk));

CREATE TABLE CSR2016
  (kbk VARCHAR(60) PRIMARY KEY,
  sr_kbk VARCHAR(60) REFERENCES SR2016(kbk),
  title TEXT);

CREATE TABLE CSR2017
  (kbk VARCHAR(60) PRIMARY KEY,
  sr_kbk VARCHAR(60) REFERENCES SR2017(kbk),
  title TEXT);

CREATE TABLE CSR2018
  (kbk VARCHAR(60) PRIMARY KEY,
  sr_kbk VARCHAR(60) REFERENCES SR2018(kbk),
  title TEXT);

CREATE TABLE CSR2019
  (kbk VARCHAR(60) PRIMARY KEY,
  sr_kbk VARCHAR(60) REFERENCES SR2019(kbk),
  title TEXT);

CREATE TABLE CSR2020
  (kbk VARCHAR(60) PRIMARY KEY,
  sr_kbk VARCHAR(60) REFERENCES SR2020(kbk),
  title TEXT);

CREATE TABLE CSR2021
  (kbk VARCHAR(60) PRIMARY KEY,
  sr_kbk VARCHAR(60) REFERENCES SR2021(kbk),
  title TEXT);

CREATE TABLE VR2016
  (kbk VARCHAR(60) PRIMARY KEY,
  csr_kbk VARCHAR(60) REFERENCES CSR2016(kbk),
  code_main_event VARCHAR(60) REFERENCES MAIN_EVENT_SR2016(code_main_event),
  title TEXT,
  approved_plan_thousand FLOAT,
  updated_plan_thousand FLOAT,
  fact_thousand FLOAT);

CREATE TABLE VR2017
  (kbk VARCHAR(60) PRIMARY KEY,
  csr_kbk VARCHAR(60) REFERENCES CSR2017(kbk),
  code_main_event VARCHAR(60) REFERENCES MAIN_EVENT_SR2017(code_main_event),
  title TEXT,
  approved_plan_thousand FLOAT,
  updated_plan_thousand FLOAT,
  fact_thousand FLOAT);

CREATE TABLE VR2018
  (kbk VARCHAR(60) PRIMARY KEY,
  csr_kbk VARCHAR(60) REFERENCES CSR2018(kbk),
  code_main_event VARCHAR(60) REFERENCES MAIN_EVENT_SR2018(code_main_event),
  title TEXT,
  approved_plan_thousand FLOAT,
  updated_plan_thousand FLOAT,
  fact_thousand FLOAT);

CREATE TABLE VR2019
  (kbk VARCHAR(60) PRIMARY KEY,
  csr_kbk VARCHAR(60) REFERENCES CSR2019(kbk),
  code_main_event VARCHAR(60) REFERENCES MAIN_EVENT_SR2019(code_main_event),
  title TEXT,
  approved_plan_thousand FLOAT,
  updated_plan_thousand FLOAT,
  fact_thousand FLOAT);

CREATE TABLE VR2020
  (kbk VARCHAR(60) PRIMARY KEY,
  csr_kbk VARCHAR(60) REFERENCES CSR2020(kbk),
  code_main_event VARCHAR(60) REFERENCES MAIN_EVENT_SR2020(code_main_event),
  title TEXT,
  approved_plan_thousand FLOAT,
  updated_plan_thousand FLOAT,
  fact_thousand FLOAT);

CREATE TABLE VR2021
  (kbk VARCHAR(60) PRIMARY KEY,
  csr_kbk VARCHAR(60) REFERENCES CSR2021(kbk),
  code_main_event VARCHAR(60) REFERENCES MAIN_EVENT_SR2021(code_main_event),
  title TEXT,
  updated_plan FLOAT,
  fact FLOAT);

SET search_path TO public;

