CREATE TABLE IMPLEMENTATION_PERIOD (
    id INTEGER PRIMARY KEY,
    period TEXT NOT NULL
);

CREATE TABLE EXPECTED_RESULT (
    id INTEGER PRIMARY KEY,
    result TEXT NOT NULL
);

CREATE TABLE FINANCING_SOURCE (
    id INTEGER PRIMARY KEY,
    source TEXT NOT NULL
);

CREATE TABLE MAIN_EVENTS (
    id TEXT PRIMARY KEY,
    id_aim TEXT REFERENCES STRATEGY_SUB_AIM(id) NOT NULL,
    id_period INTEGER REFERENCES IMPLEMENTATION_PERIOD(id) NOT NULL,
    id_result INTEGER REFERENCES FINANCING_SOURCE(id) NOT NULL,
    id_prog TEXT REFERENCES GOSPROGRAM(id),
    main_event TEXT NOT NULL
);

CREATE TABLE ALL_EVENTS (
    id TEXT PRIMARY KEY,
    id_period INTEGER REFERENCES IMPLEMENTATION_PERIOD(id) NOT NULL,
    id_result INTEGER REFERENCES FINANCING_SOURCE(id) NOT NULL,
    id_prog TEXT REFERENCES GOSPROGRAM(id),
    sub_event TEXT NOT NULL
);

