CREATE TABLE GOSPROGRAM(
    id VARCHAR(60) PRIMARY KEY,
    title_prog TEXT NOT NULL
);

CREATE TABLE AIM_AND_GOSPROGRAM(
    id_aim INTEGER REFERENCES STRATEGY_AIM(id),
    id_prog VARCHAR(60) REFERENCES GOSPROGRAM(id)
);