CREATE TABLE RESPONSE_OBJ2016
  (id INTEGER PRIMARY KEY,
  response_obj TEXT NOT NULL);
  
CREATE TABLE RESPONSE_FIO2016
  (id INTEGER PRIMARY KEY,
  id_response INTEGER REFERENCES RESPONSE_OBJ(id) NOT NULL,
  fio VARCHAR(255) NOT NULL);

CREATE TABLE ALL_EVENTS2016
  (code VARCHAR(60) PRIMARY KEY,
  id_response INTEGER REFERENCES RESPONSE_OBJ(id) NOT NULL,
  id_fio INTEGER REFERENCES RESPONSE_FIO(id) NOT NULL,
  events TEXT NOT NULL);

CREATE TABLE GOSPROGRAM2016
  (id_prog VARCHAR(60) PRIMARY KEY REFERENCES ALL_EVENTS(code),
  title_prog TEXT NOT NULL);
  
CREATE TABLE SUBPROGRAM2016
  (code VARCHAR(60) PRIMARY KEY REFERENCES ALL_EVENTS(code),
  id_prog VARCHAR(60) REFERENCES GOSPROGRAM(id_prog) NOT NULL,
  title_subprog TEXT NOT NULL);
  
CREATE TABLE MAIN_EVENT2016
  (code VARCHAR(60) PRIMARY KEY REFERENCES ALL_EVENTS(code),
  code_subprog VARCHAR(60) REFERENCES SUBPROGRAM(code) NOT NULL,
  main_event TEXT NOT NULL);
  
CREATE TABLE EVENT2016
  (code VARCHAR(60) PRIMARY KEY REFERENCES ALL_EVENTS(code),
  code_main_event VARCHAR(60) REFERENCES MAIN_EVENT(code) NOT NULL,
  event_ TEXT NOT NULL);
