CREATE TABLE STRATEGY_SUB_AIM
    (id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    aim_id INTEGER REFERENCES STRATEGY_AIM(id));

CREATE TABLE STRATEGY_TASKS
    (id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    sub_aim_id TEXT REFERENCES STRATEGY_SUB_AIM(id));

