CREATE TABLE ITEMS
  (id INTEGER PRIMARY KEY,
  expense_item TEXT NOT NULL);
  
CREATE TABLE CATEGORIES
  (id INTEGER PRIMARY KEY,
  category TEXT NOT NULL);
  
CREATE TABLE EXPENSES
  (id INTEGER PRIMARY KEY,
  code_events TEXT REFERENCES ALL_EVENTS(code),
  item_id INTEGER REFERENCES ITEMS(id),
  category_id INTEGER REFERENCES CATEGORIES(id),
  fed FLOAT,
  obl FLOAT);
